### ISSUE TITLE
Error about dataset

### ISSUE THREAD

**Issue by zimingzhong** [crockwell/pixelsynth#1]
I try to obtain your subset dataset by filling the form several times without any email reply. Is that an error about my email or something else? Thank you!

**Comment by crockwell** [comment]
Hi Ziming,

Thanks for bringing this up! For some reason I was not getting a notification you filled out the form. I've shared the frames with you now, please let me know if there is any more issues.

Best,
Chris

**Comment by zimingzhong** [comment]
Hi Chris,

Thank you for your patience and active reply. I already receive the test dataset. Do you have a future plan for releasing the training dataset and validation dataset for a fair comparison? 
Thank you again for your reply.

Best,
Ziming

**Comment by crockwell** [comment]
Ziming,

No problem! No we will not release train and validation frames since they are randomly selected from a very, very large set. On RealEstate10K, pairs of frames are selected from a huge number of videos; on Matterport an embodied agent randomly navigates to collect pairs. 
Randomness of selection from these sets during training should not significantly affect results.

Best,
Chris

**Comment by zimingzhong** [comment]
Hi Chris

Thank you for your nice answer. That has solved my current problem. Thank you!

Best,
Ziming

**Comment by crockwell** [comment]
No problem - glad I could help!
